// GENERATED by `providers::catalog_mirror_source` in src-tauri/src/providers.rs.
// Do not edit: change the registry row and run
//   KLIDE_WRITE_MIRROR=1 cargo test provider_catalog_mirror_is_current
// The `provider_catalog_mirror_is_current` test fails the build when
// this file and the Rust registry disagree.
//
// Each row is one `ProviderEntry`, exactly as `ai_list_providers` returns
// it. See src/agent/providerCatalog.ts for the typed accessors.
export const PROVIDER_ROWS = [
  {
    "id": "ollama",
    "label": "Ollama",
    "shortLabel": null,
    "group": "local",
    "wire": "ollama",
    "keyEnv": null,
    "keyEnvLegacy": null,
    "keyPlaceholder": null,
    "defaultModel": "llama3.1:8b",
    "presets": [
      "pierreprudh/klide-8b"
    ],
    "brand": "ollama",
    "hasCredits": false,
    "isLocalServer": true,
    "hasNumCtx": true,
    "caps": {
      "structuredReplay": false,
      "minimalChatContext": true,
      "appendTodoUpdates": false
    },
    "contextWindow": null
  },
  {
    "id": "mlx",
    "label": "MLX (Apple Silicon)",
    "shortLabel": "MLX",
    "group": "local",
    "wire": "openai",
    "keyEnv": null,
    "keyEnvLegacy": null,
    "keyPlaceholder": null,
    "defaultModel": "mlx-community/Llama-3.1-8B-Instruct-4bit",
    "presets": [
      "mlx-community/Llama-3.1-8B-Instruct-4bit",
      "Qwen/Qwen3-4B-MLX-4bit",
      "mlx-community/gemma-2-9b-it-4bit",
      "mlx-community/gemma-4-E4B-it-qat-4bit",
      "mlx-community/gemma-4-12B-it-qat-4bit"
    ],
    "brand": "mlx",
    "hasCredits": false,
    "isLocalServer": true,
    "hasNumCtx": false,
    "caps": {
      "structuredReplay": true,
      "minimalChatContext": true,
      "appendTodoUpdates": true
    },
    "contextWindow": 128000
  },
  {
    "id": "llamacpp",
    "label": "llama.cpp",
    "shortLabel": null,
    "group": "local",
    "wire": "openai",
    "keyEnv": null,
    "keyEnvLegacy": null,
    "keyPlaceholder": null,
    "defaultModel": "pierreprudh/klide-8b",
    "presets": [],
    "brand": "llamacpp",
    "hasCredits": false,
    "isLocalServer": true,
    "hasNumCtx": false,
    "caps": {
      "structuredReplay": true,
      "minimalChatContext": true,
      "appendTodoUpdates": true
    },
    "contextWindow": 8192
  },
  {
    "id": "lmstudio",
    "label": "LM Studio",
    "shortLabel": null,
    "group": "local",
    "wire": "openai",
    "keyEnv": null,
    "keyEnvLegacy": null,
    "keyPlaceholder": null,
    "defaultModel": "local-model",
    "presets": [],
    "brand": "lmstudio",
    "hasCredits": false,
    "isLocalServer": false,
    "hasNumCtx": false,
    "caps": {
      "structuredReplay": true,
      "minimalChatContext": false,
      "appendTodoUpdates": false
    },
    "contextWindow": null
  },
  {
    "id": "anthropic",
    "label": "Anthropic",
    "shortLabel": null,
    "group": "hosted",
    "wire": "anthropic",
    "keyEnv": "ANTHROPIC_API_KEY",
    "keyEnvLegacy": null,
    "keyPlaceholder": "sk-ant-...",
    "defaultModel": "claude-sonnet-4-6",
    "presets": [],
    "brand": "anthropic",
    "hasCredits": false,
    "isLocalServer": false,
    "hasNumCtx": false,
    "caps": {
      "structuredReplay": true,
      "minimalChatContext": false,
      "appendTodoUpdates": false
    },
    "contextWindow": null
  },
  {
    "id": "openai",
    "label": "OpenAI",
    "shortLabel": null,
    "group": "hosted",
    "wire": "openai",
    "keyEnv": "OPENAI_API_KEY",
    "keyEnvLegacy": null,
    "keyPlaceholder": "sk-...",
    "defaultModel": "gpt-4.1",
    "presets": [],
    "brand": "openai",
    "hasCredits": false,
    "isLocalServer": false,
    "hasNumCtx": false,
    "caps": {
      "structuredReplay": true,
      "minimalChatContext": false,
      "appendTodoUpdates": false
    },
    "contextWindow": null
  },
  {
    "id": "mistral",
    "label": "Mistral",
    "shortLabel": null,
    "group": "hosted",
    "wire": "openai",
    "keyEnv": "MISTRAL_API_KEY",
    "keyEnvLegacy": null,
    "keyPlaceholder": "...",
    "defaultModel": "mistral-large-latest",
    "presets": [],
    "brand": "mistral",
    "hasCredits": false,
    "isLocalServer": false,
    "hasNumCtx": false,
    "caps": {
      "structuredReplay": true,
      "minimalChatContext": false,
      "appendTodoUpdates": false
    },
    "contextWindow": null
  },
  {
    "id": "xai",
    "label": "xAI Grok",
    "shortLabel": "xAI",
    "group": "hosted",
    "wire": "openai",
    "keyEnv": "XAI_API_KEY",
    "keyEnvLegacy": "GROK_API_KEY",
    "keyPlaceholder": "xai-...",
    "defaultModel": "grok-4",
    "presets": [],
    "brand": "xai",
    "hasCredits": false,
    "isLocalServer": false,
    "hasNumCtx": false,
    "caps": {
      "structuredReplay": true,
      "minimalChatContext": false,
      "appendTodoUpdates": false
    },
    "contextWindow": null
  },
  {
    "id": "deepseek",
    "label": "DeepSeek",
    "shortLabel": null,
    "group": "hosted",
    "wire": "openai",
    "keyEnv": "DEEPSEEK_API_KEY",
    "keyEnvLegacy": null,
    "keyPlaceholder": "sk-...",
    "defaultModel": "deepseek-chat",
    "presets": [],
    "brand": "deepseek",
    "hasCredits": true,
    "isLocalServer": false,
    "hasNumCtx": false,
    "caps": {
      "structuredReplay": true,
      "minimalChatContext": false,
      "appendTodoUpdates": false
    },
    "contextWindow": null
  },
  {
    "id": "openrouter",
    "label": "OpenRouter",
    "shortLabel": null,
    "group": "hosted",
    "wire": "openai",
    "keyEnv": "OPENROUTER_API_KEY",
    "keyEnvLegacy": null,
    "keyPlaceholder": "sk-or-...",
    "defaultModel": "openai/gpt-4o",
    "presets": [],
    "brand": "openrouter",
    "hasCredits": true,
    "isLocalServer": false,
    "hasNumCtx": false,
    "caps": {
      "structuredReplay": true,
      "minimalChatContext": false,
      "appendTodoUpdates": false
    },
    "contextWindow": null
  },
  {
    "id": "claude-code",
    "label": "Claude Code",
    "shortLabel": null,
    "group": "subscription",
    "wire": "delegate",
    "keyEnv": null,
    "keyEnvLegacy": null,
    "keyPlaceholder": null,
    "defaultModel": null,
    "presets": [],
    "brand": "claude-code",
    "hasCredits": false,
    "isLocalServer": false,
    "hasNumCtx": false,
    "caps": {
      "structuredReplay": true,
      "minimalChatContext": false,
      "appendTodoUpdates": false
    },
    "contextWindow": 200000
  },
  {
    "id": "codex",
    "label": "Codex",
    "shortLabel": null,
    "group": "subscription",
    "wire": "delegate",
    "keyEnv": null,
    "keyEnvLegacy": null,
    "keyPlaceholder": null,
    "defaultModel": null,
    "presets": [],
    "brand": "codex",
    "hasCredits": false,
    "isLocalServer": false,
    "hasNumCtx": false,
    "caps": {
      "structuredReplay": true,
      "minimalChatContext": false,
      "appendTodoUpdates": false
    },
    "contextWindow": 272000
  },
  {
    "id": "opencode",
    "label": "OpenCode",
    "shortLabel": null,
    "group": "subscription",
    "wire": "delegate",
    "keyEnv": null,
    "keyEnvLegacy": null,
    "keyPlaceholder": null,
    "defaultModel": null,
    "presets": [],
    "brand": "opencode",
    "hasCredits": false,
    "isLocalServer": false,
    "hasNumCtx": false,
    "caps": {
      "structuredReplay": true,
      "minimalChatContext": false,
      "appendTodoUpdates": false
    },
    "contextWindow": null
  },
  {
    "id": "omp",
    "label": "Oh My Pi",
    "shortLabel": null,
    "group": "subscription",
    "wire": "delegate",
    "keyEnv": null,
    "keyEnvLegacy": null,
    "keyPlaceholder": null,
    "defaultModel": null,
    "presets": [],
    "brand": "omp",
    "hasCredits": false,
    "isLocalServer": false,
    "hasNumCtx": false,
    "caps": {
      "structuredReplay": true,
      "minimalChatContext": false,
      "appendTodoUpdates": false
    },
    "contextWindow": null
  }
] as const;
